#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: Tailor Vijay

# Short bio or description (displayed in the header)
description: Digital distribution channel specialist. Grassroots media and Open-Source advocate. Activist.

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: http://www.gravatar.com/avatar/3b47685ab3401a967953ee296225027b

#
# Flags below are optional
#

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble: 
  email: tailor.vj@gmail.com
  facebook: tailorvj
  flickr: 
  github: tailorvj/tailorvj.github.com
  instagram: tailorvj
  linkedin: 
  pinterest: tailorvj
  rss: # just type anything here for a working RSS icon, make sure you set the "url" above!
  twitter: tailorvj
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"

# Your disqus shortname, entering this will enable commenting on posts
disqus: 

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: 

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: http://tailorvj.github.io

# If you're hosting your site at a Project repository on GitHub pages 
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

#
# !! You don't need to change any of the configuration flags below !!
#

markdown: kramdown
highlighter: pygments
permalink: /:title/

# The release of Jekyll Now that you're using
version: v1.0.0

# Set the Sass partials directory, as we're using @imports
sass:
  sass_dir: _scss
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
gems:
- jekyll-mentions
- jemoji
- jekyll-redirect-from
- jekyll-sitemap

# Exclude these files from your production _site
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
